from __future__ import annotations

import os
from typing import Optional


class SnapshotPdfExternalUnavailable(RuntimeError):
    """Raised when the external visual PDF converter cannot be used safely."""


def converter_url() -> str:
    """Return the configured external converter base URL, without trailing slash."""
    return (os.getenv("SNAPSHOT_PDF_CONVERTER_URL") or "").strip().rstrip("/")


def converter_token() -> str:
    return (os.getenv("SNAPSHOT_PDF_CONVERTER_TOKEN") or "").strip()


def external_converter_available() -> bool:
    return bool(converter_url())


def generate_pdf_from_snapshot_html(html_bytes: bytes, *, timeout_seconds: int = 75) -> bytes:
    """Convert the already-generated visual snapshot HTML into a PDF using an external service.

    This function intentionally receives the HTML generated by core.snapshot_pdf so the app
    preserves the current visual identity and does not duplicate report rendering logic.
    Heavy browser/PDF dependencies stay outside the main Streamlit app.
    """
    url = converter_url()
    if not url:
        raise SnapshotPdfExternalUnavailable(
            "PDF visual automático indisponível neste ambiente. Use o HTML visual e imprima/salve em PDF pelo navegador."
        )

    html_text = (html_bytes or b"").decode("utf-8", errors="replace").strip()
    if not html_text:
        raise SnapshotPdfExternalUnavailable("O HTML visual do snapshot está vazio e não pode ser convertido em PDF.")

    headers = {"Content-Type": "application/json"}
    token = converter_token()
    if token:
        headers["Authorization"] = f"Bearer {token}"

    endpoint = f"{url}/render-snapshot-pdf"
    try:
        import requests

        response = requests.post(
            endpoint,
            json={"html": html_text},
            headers=headers,
            timeout=timeout_seconds,
        )
    except Exception as exc:
        raise SnapshotPdfExternalUnavailable(
            "O conversor externo de PDF visual não respondeu. O HTML visual foi mantido como alternativa segura."
        ) from exc

    content_type = (response.headers.get("content-type") or "").lower()
    if response.status_code != 200 or "application/pdf" not in content_type:
        detail = (getattr(response, "text", "") or "sem detalhes")[:300]
        raise SnapshotPdfExternalUnavailable(
            "O conversor externo não conseguiu gerar o PDF visual agora. "
            f"Detalhe técnico: {detail}"
        )

    pdf_bytes = response.content or b""
    if not pdf_bytes.startswith(b"%PDF"):
        raise SnapshotPdfExternalUnavailable(
            "O conversor externo respondeu, mas o arquivo retornado não parece ser um PDF válido."
        )
    return pdf_bytes
