from .item_00_intro import render as render_item_00_intro
from .item_01_localizacao import render as render_item_01
from .item_02_adequabilidade import render as render_item_02
from .item_03_leitura_adequabilidade import render as render_item_03
from .item_04_zona import render as render_item_04
from .item_05_regras_principais import render as render_item_05
from .item_06_ocupacao_terreo import render as render_item_06
from .item_07_permeabilidade import render as render_item_07
from .item_08_ia_altura import render as render_item_08
from .item_09_vagas import render as render_item_09
from .item_10_quadro_tecnico import render as render_item_10
from .item_11_calcada import render as render_item_11
from .item_12_dicas import render as render_item_12
from .item_13_resumo import render as render_item_13
from .item_14_pos_etapa import render as render_item_14
from .item_15_fechamento import render as render_item_15
from .item_16_fechamento import render as render_item_16
