window.AUTH_CONFIG = {
  SUPABASE_URL: "",
  SUPABASE_ANON_KEY: "",
  GATEWAY_BASE_URL: "",
  LOGIN_REDIRECT_URL: "",
  STREAMLIT_APP_URL: "",
  ALLOWED_STREAMLIT_ORIGINS: [],
  ALLOWED_GATEWAY_ORIGINS: [],
  ALLOWED_LOGIN_REDIRECT_ORIGINS: []
};
